import { basicColor } from './basicColor';

export const palette = {
  primary: {
    light10: basicColor.primary.skyBlue[10],
    light20: basicColor.primary.skyBlue[20],
    light30: basicColor.primary.skyBlue[30],
    light: basicColor.primary.skyBlue[60],
    main: basicColor.primary.skyBlue[70],
    dark: basicColor.primary.skyBlue[90],
  },
  secondary: {
    light10: basicColor.primary.yellow[10],
    light20: basicColor.primary.yellow[20],
    light30: basicColor.primary.yellow[30],
    light: basicColor.primary.yellow[50],
    main: basicColor.primary.yellow[60],
    dark: basicColor.primary.yellow[80],
  },
  success: {
    bg: basicColor.secondary.green[10],
    light: basicColor.secondary.green[20],
    hover: basicColor.secondary.green[50],
    main: basicColor.secondary.green[70],
    dark: basicColor.secondary.green[80],
  },
  error: {
    bg: basicColor.secondary.red[10],
    light: basicColor.secondary.red[20],
    hover: basicColor.secondary.red[50],
    main: basicColor.secondary.red[60],
    dark: basicColor.secondary.red[90],
  },
  warning: {
    bg: basicColor.primary.tangerineOrange[10],
    light: basicColor.primary.tangerineOrange[20],
    hover: basicColor.primary.tangerineOrange[50],
    main: basicColor.primary.tangerineOrange[60],
    dark: basicColor.primary.tangerineOrange[90],
  },
  white: { main: basicColor.achromatic.white },
  black: { main: basicColor.achromatic.black },
  gray: {
    disableDark: basicColor.achromatic.gray[20],
    disableLight: basicColor.achromatic.gray[5],
    selected: basicColor.achromatic.gray[10],
    active: basicColor.achromatic.gray[5],
    hover: basicColor.achromatic.gray[3],
    borderLight: basicColor.achromatic.gray[10],
    border: basicColor.achromatic.gray[20],
    borderDark: basicColor.achromatic.gray[30],
  },
  colorKit: {
    light: {
      1: basicColor.primary.navyBlue[20],
      2: basicColor.primary.skyBlue[10],
      3: basicColor.secondary.turquoiseBlue[10],
      4: basicColor.secondary.green[10],
      5: basicColor.secondary.emeraldGreen[10],
      6: basicColor.primary.tangerineOrange[10],
      7: basicColor.primary.lanternOrange[20],
      8: basicColor.secondary.red[10],
      9: basicColor.primary.fuchsia[10],
      10: basicColor.secondary.purple[10],
      11: basicColor.achromatic.gray[5],
    },
    main: {
      1: basicColor.primary.navyBlue[50],
      2: basicColor.primary.skyBlue[30],
      3: basicColor.secondary.turquoiseBlue[40],
      4: basicColor.secondary.green[60],
      5: basicColor.secondary.emeraldGreen[40],
      6: basicColor.primary.tangerineOrange[40],
      7: basicColor.primary.lanternOrange[50],
      8: basicColor.secondary.red[30],
      9: basicColor.primary.fuchsia[30],
      10: basicColor.secondary.purple[40],
      11: basicColor.achromatic.gray[30],
    },
    dark: {
      1: basicColor.primary.navyBlue[60],
      2: basicColor.primary.skyBlue[50],
      3: basicColor.secondary.turquoiseBlue[60],
      4: basicColor.secondary.green[70],
      5: basicColor.secondary.emeraldGreen[60],
      6: basicColor.primary.tangerineOrange[60],
      7: basicColor.primary.lanternOrange[60],
      8: basicColor.secondary.red[60],
      9: basicColor.primary.fuchsia[60],
      10: basicColor.secondary.purple[60],
      11: basicColor.achromatic.gray[60],
    },
  },
  text: {
    primary: basicColor.achromatic.gray[90],
    secondary: basicColor.achromatic.gray[70],
    hint: basicColor.achromatic.gray[30],
    link: basicColor.primary.skyBlue[60],
  },
  background: {
    page: basicColor.primary.skyBlue[10],
  },
} as const;
