apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.website.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels: {{- include "app.website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.website.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.website.service.port }}
      targetPort: {{ .Values.website.service.targetPort }}
      name: http
  selector: {{- include "app.website.labels" . | nindent 4 }}
